未入力チェック機能の追加
Freedom645/sekai-rec pull request #21
Opened 2023-10-04 01:30 UTC by mIUraKeItA005

レビューお願いします
三浦

2023-10-04 01:51 UTC, Freedom645 requested changes
@mIUraKeItA005 
レビューしたので見てね

2023-10-04 01:51 UTC, Freedom645 commented on src/views/ScoreRegisterView.vue
> +  console.log(checkItems);
@mIUraKeItA005 
コンソール出力の削除お願い！

2023-10-04 01:51 UTC, Freedom645 commented on src/views/ScoreRegisterView.vue
>      return;
@mIUraKeItA005 
「登録しますか？」の確認前に未入力のメッセージ出した方が親切かも。

2023-10-04 01:51 UTC, Freedom645 commented on src/views/ScoreRegisterView.vue
> +
@mIUraKeItA005 
空白の差分が出てるから、もしかするとフォーマッタがかかってないかもしれない？
（余分な空白はフォーマッタが削除してくれるはず）

2023-10-06 03:40 UTC, mIUraKeItA005 commented
> @mIUraKeItA005 最初のif文は削除して良いかも。
> 
> ```ts
> const registerScore = async () => {
>   if (music.value?.id === undefined || difficulty.value?.rank === undefined) {
>     return;
>   }
> ```

2023-10-06 03:40 UTC, closed without merging

2023-10-06 03:41 UTC, mIUraKeItA005 commented
> @mIUraKeItA005 最初のif文は削除して良いかも。
> 
> ```ts
> const registerScore = async () => {
>   if (music.value?.id === undefined || difficulty.value?.rank === undefined) {
>     return;
>   }
> ```

消去済み